// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrate/introspection need the direct (non-pooled) connection.
    // The runtime client uses DATABASE_URL (pooled) via the Neon adapter instead — see src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
